[functions.generate-phrase]
verify_jwt = true

[functions.instant-composition-generate]
verify_jwt = true

[functions.instant-composition-evaluate]
verify_jwt = true

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []
enable_anonymous_sign_ins = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[storage.vector]
enabled = false
